trigger: none  # Запуск только вручную или по расписанию
schedules:
  - cron: "0 0 * * *"  # Запуск каждый день в 00:00 UTC
    displayName: "Очистка старых веток"
    branches:
      include:
        - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: PowerShell@2
    displayName: 'Удаление старых веток'
    inputs:
      targetType: 'inline'
      script: |
        # === Конфигурация ===
        $org = "your-org"          # Имя организации в Azure DevOps
        $project = "your-project"  # Имя проекта
        $token = "$(System.AccessToken)"  # Получение PAT через систему Azure DevOps
        $branch = "refs/heads/main" # Основная ветка для политики

        # === Получаем все репозитории ===
        $headers = @{Authorization = "Basic " + [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":$token"))}
        $repos = Invoke-RestMethod -Uri "https://dev.azure.com/$org/$project/_apis/git/repositories?api-version=7.1-preview.1" -Headers $headers -Method Get

        # Фильтруем репозитории по префиксу 'mana-'
        $filteredRepos = $repos.value | Where-Object { $_.name -match "^mana-.*" }

        foreach ($repo in $filteredRepos) {
            Write-Host "Проверка репозитория: $($repo.name)"
            
            # Получаем все ветки
            $branches = Invoke-RestMethod -Uri "https://dev.azure.com/$org/$project/_apis/git/repositories/$($repo.id)/refs?filter=heads/&api-version=7.1-preview.1" -Headers $headers -Method Get

            foreach ($branch in $branches.value) {
                # Пропускаем главные ветки
                if ($branch.name -eq "refs/heads/main" -or $branch.name -eq "refs/heads/develop") {
                    continue
                }

                # Получаем дату последнего коммита для ветки
                $lastCommitDate = Invoke-RestMethod -Uri "https://dev.azure.com/$org/$project/_apis/git/repositories/$($repo.id)/commits?searchCriteria.itemVersion.version=${branch.name#refs/heads/}&$top=1&api-version=7.1-preview.1" -Headers $headers -Method Get
                $lastCommitDate = $lastCommitDate.value[0].author.date

                # Рассчитываем возраст ветки (в днях)
                $branchAge = (New-TimeSpan -Start (Get-Date $lastCommitDate) -End (Get-Date)).Days

                # Если ветка старше 21 дня, удаляем её
                if ($branchAge -gt 21) {
                    Write-Host "🗑 Удаляем ветку $($branch.name), возраст: $branchAge дней"
                    # Удаляем ветку
                    Invoke-RestMethod -Uri "https://dev.azure.com/$org/$project/_apis/git/repositories/$($repo.id)/refs?filter=${branch.name#refs/heads/}&api-version=7.1-preview.1" -Headers $headers -Method Delete
                }
            }
        }
    displayName: "Удаление старых веток из репозиториев с префиксом mana-"
