trigger: none  # Запуск только вручную или по расписанию
schedules:
  - cron: "0 0 * * *"  # Запуск каждый день в 00:00 UTC
    displayName: "Очистка старых веток"
    branches:
      include:
        - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: PowerShell@2
    displayName: 'Удаление старых веток'
    inputs:
      targetType: 'inline'
      script: |
  # === Конфигурация ===
  $org = "your-org"          # Имя организации в Azure DevOps
  $project = "your-project"  # Имя проекта
  $token = "$(System.AccessToken)"  # Получение PAT через систему Azure DevOps
  $daysOld = 21  # Порог "устаревших" веток (в днях)

  # === Константы API ===
  $API_BASE_URL = "https://dev.azure.com/$org/$project/_apis/git/repositories"

  # === Получаем все репозитории ===
  $headers = @{Authorization = "Basic " + [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":$token"))}
  $repos = Invoke-RestMethod -Uri "$API_BASE_URL?api-version=7.1-preview.1" -Headers $headers -Method Get

  # Фильтруем репозитории по префиксу 'mana-'
  $filteredRepos = $repos.value | Where-Object { $_.name -match "^mana-.*" }

  # === Выводим список веток для каждого репозитория ===
  foreach ($repo in $filteredRepos) {
      Write-Host "`n🔹 Репозиторий: $($repo.webUrl)"

      # Получаем список веток
      $branchesUri = "$API_BASE_URL/$($repo.id)/refs?filter=heads/&api-version=7.1-preview.1"
      $branches = Invoke-RestMethod -Uri $branchesUri -Headers $headers -Method Get

      # Текущая дата для сравнения
      $currentDate = Get-Date

      # Флаг для проверки, есть ли устаревшие ветки
      $hasOldBranches = $false

      # Проверяем каждую ветку
      foreach ($branch in $branches.value) {
          $branchName = $branch.name -replace 'refs/heads/', ''

          # Пропускаем master и main
          if ($branchName -in @("master", "main")) {
              continue
          }

          # Получаем информацию о последнем коммите
          $commitUri = "$API_BASE_URL/$($repo.id)/commits?searchCriteria.itemVersion.version=$branchName&`$top=1&api-version=7.1-preview.1"
          $commitInfo = Invoke-RestMethod -Uri $commitUri -Headers $headers -Method Get

          # Если нет коммитов, пропускаем
          if (-not $commitInfo.value) {
              Write-Host "    - $branchName (⚠️ Нет коммитов!)"
              continue
          }

          # Дата последнего коммита
          $lastCommitDate = Get-Date $commitInfo.value[0].author.date

          # Проверяем, если коммит был сделан более 30 дней назад
          $daysSinceLastCommit = ($currentDate - $lastCommitDate).Days
          if ($daysSinceLastCommit -ge $daysOld) {
              if (-not $hasOldBranches) {
                  Write-Host "  ⚠️  Устаревшие ветки (существуют $daysOld+ дней без коммитов):"
                  $hasOldBranches = $true
              }
              Write-Host "    - $branchName (Последний коммит: $lastCommitDate, $daysSinceLastCommit дней назад)"
          }
      }

      # Если устаревших веток нет
      if (-not $hasOldBranches) {
          Write-Host "  ✅ Нет устаревших веток"
      }
  }
